<template><div><h1 id="如何在vue3引入live2d" tabindex="-1"><a class="header-anchor" href="#如何在vue3引入live2d"><span>如何在vue3引入live2d</span></a></h1>
<p>这是一篇关于如何在vue3部署liv2d的文档<br>
基于guansss大佬开发的<a href="https://github.com/guansss/pixi-live2d-display" target="_blank" rel="noopener noreferrer">pixi-live2d-display@0.5.0-beta</a>库来构建<br>
如需立即获得一个live2d基础框架,请点击该网址,<a href="https://github.com/fish-bread/vue-live2d" target="_blank" rel="noopener noreferrer">fish-bread的live2d项目</a></p>
<h2 id="使用技术" tabindex="-1"><a class="header-anchor" href="#使用技术"><span>使用技术</span></a></h2>
<ol>
<li>vue3</li>
<li><a href="https://pixijs.com/7.x/guides" target="_blank" rel="noopener noreferrer">pixi.js@7.4.3</a></li>
<li><a href="https://github.com/guansss/pixi-live2d-display" target="_blank" rel="noopener noreferrer">pixi-live2d-display@0.5.0-beta</a></li>
<li>live2dcubism的用于web的脚本文件(live2dcubismcore.min.js和live2d.min.js)<br>
<a href="https://github.com/fish-bread/vue-live2d/blob/main/src/live2d.min.js" target="_blank" rel="noopener noreferrer">live2d.min.js的文件链接</a><br>
<a href="https://github.com/fish-bread/vue-live2d/blob/main/src/live2dcubismcore.min.js" target="_blank" rel="noopener noreferrer">live2dcubismcore.min.js的文件链接</a></li>
</ol>
<h2 id="配置依赖" tabindex="-1"><a class="header-anchor" href="#配置依赖"><span>配置依赖</span></a></h2>
<ol>
<li>首先将需要的包进行下载</li>
</ol>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#5c6a72;--shiki-dark:#d3c6aa;--shiki-light-bg:#fdf6e3;--shiki-dark-bg:#2d353b"><pre class="shiki shiki-themes everforest-light everforest-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> npm</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> install</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> pixi.js@7.4.3</span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> npm</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> install</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> pixi-live2d-display@0.5.0-beta</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>将两个运行脚本下载到项目中(推荐下载到public文件夹)</li>
<li>在index.html文件中引入(将图中的路径替换为你的路径)
<img src="/markdown_img/vue/vue_live2d_index.png" alt="index.html配置图片" title="index.html配置图片"></li>
<li>将你所需要运行的单个live2d文件放在public文件夹中</li>
</ol>
<h2 id="live2d文件介绍" tabindex="-1"><a class="header-anchor" href="#live2d文件介绍"><span>live2d文件介绍</span></a></h2>
<ol>
<li>model3.json文件(或model.json文件),本次部署live2d模型的<strong>核心文件</strong>.在该文件中记录;了有关live2d模型的
<ol>
<li>动作列表[Motion],<strong>用于记录触发什么动作</strong></li>
<li>语言列表[Motion列表下每个动作file路径下的对应的Sound],<strong>用于记录触发相应动作时的音频路径</strong>,</li>
</ol>
<blockquote>
<p>注意:语音无需主动触发,当动作执行时,语音会自动触发,当然,如果有的话</p>
</blockquote>
<ol start="3">
<li>表情列表[expressioon],<strong>用于记录触发什么表情，表情列表不跟随动作一同进行</strong>
<img src="/markdown_img/vue/motion.png" alt="motion图片" title="motion图片">
<img src="/markdown_img/vue/express.png" alt="express图片" title="express图片"></li>
</ol>
</li>
</ol>
<h2 id="组件引入" tabindex="-1"><a class="header-anchor" href="#组件引入"><span>组件引入</span></a></h2>
<h3 id="在你要引入的组件中引入" tabindex="-1"><a class="header-anchor" href="#在你要引入的组件中引入"><span>在你要引入的组件中引入</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="shiki" data-ext="javascript" style="--shiki-light:#5c6a72;--shiki-dark:#d3c6aa;--shiki-light-bg:#fdf6e3;--shiki-dark-bg:#2d353b"><pre class="shiki shiki-themes everforest-light everforest-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">import</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> *</span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80"> as</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> PIXI </span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">from</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> 'pixi.js'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">;</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//所有引入</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">import</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> { Live2DModel } </span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">from</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> 'pixi-live2d-display'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">;</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//只需要 Cubism 2.1</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//import { Live2DModel } from 'pixi-live2d-display/cubism2';</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//只需要 Cubism 4</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//import { Live2DModel } from 'pixi-live2d-display/cubism4';</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建相关对象" tabindex="-1"><a class="header-anchor" href="#创建相关对象"><span>创建相关对象</span></a></h3>
<blockquote>
<p>其中,model_list用于编写<strong>模型名字</strong>,<strong>模型文件路径</strong>(一般为模型文件下的'模型名.model3.json'或'模型名.model.json'),<strong>模型缩放大小</strong></p>
</blockquote>
<div class="language-javascript line-numbers-mode" data-highlighter="shiki" data-ext="javascript" style="--shiki-light:#5c6a72;--shiki-dark:#d3c6aa;--shiki-light-bg:#fdf6e3;--shiki-dark-bg:#2d353b"><pre class="shiki shiki-themes everforest-light everforest-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//将 PIXI 暴露到 window 对象，以便运行库能够一次使用全部方法</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">window</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">PIXI </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> PIXI;</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//为了存储pixi实例</span></span>
<span class="line"><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">const</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> app </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> ref</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">()</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//为了存储live2d实例</span></span>
<span class="line"><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">const</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> model </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> ref</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">()</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//便签绑定</span></span>
<span class="line"><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">const</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> liveCanvas </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> shallowRef</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">();</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//模型是否运动</span></span>
<span class="line"><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">const</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> is_moving </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> ref</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">()</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//模型列表</span></span>
<span class="line"><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">const</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> model_list </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> ref</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">([</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    {model_name</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> "none"</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, model_path</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> "none"</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, scale_set</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> "none"</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">},</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">])</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建函数用于加载模型" tabindex="-1"><a class="header-anchor" href="#创建函数用于加载模型"><span>创建函数用于加载模型</span></a></h3>
<blockquote>
<p>这里我使用了model.value.motion('任意动作对象名称'),用于点击模型触发动画,你也可以自己使用model.value.motion(selectedMotion,motionNum)去绑定你的函数来执行动作</p>
</blockquote>
<div class="language-javascript line-numbers-mode" data-highlighter="shiki" data-ext="javascript" style="--shiki-light:#5c6a72;--shiki-dark:#d3c6aa;--shiki-light-bg:#fdf6e3;--shiki-dark-bg:#2d353b"><pre class="shiki shiki-themes everforest-light everforest-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">// 加载模型的函数</span></span>
<span class="line"><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">const</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> loadModel</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875"> =</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875"> async</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> (index) </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=></span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">    // 如果已经有模型存在，先销毁</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">    if</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> (model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value) {</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        app</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">stage</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">removeChild</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value);</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">destroy</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">();</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> null</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">;</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    }</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">    // 加载新模型</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">    if</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> (model_list</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value[index]</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">model_path </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">!==</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> "none"</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">) {</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">        // 这里是放live2d资源的地方，直接相对路径引用即可</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">       // 导入后缀为.model3.json的json文件路径</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80"> await</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> Live2DModel</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">from</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(model_list</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value[index]</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">model_path); </span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">        // 直接引入模型</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        app</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">stage</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">addChild</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value);</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">        // 调整缩放比例,0.1-0.2整体比较合适,要每个模型具体调整</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">scale</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">set</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(model_list</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value[index]</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">scale_set); </span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">        /* 调整渲染位置,要每个模型具体调整</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">         model.value.position.set(window.innerWidth / 5, window.innerHeight / 60); */</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">autoInteract </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> true</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">; </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">// 启用自动交互</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    }</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">    //模型构建</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">    if</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> (</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">!</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value) </span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">return</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">    // 添加点击事件监听</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">on</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F">'pointerdown'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, (event) </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=></span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        console</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">log</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F">'模型被点击'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, event</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">data</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">global);</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">        // 触发点击动作（例如触摸身体）</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">        if</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> (model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">&#x26;&#x26;</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> is_moving</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">===</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> false</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> ) {</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">            console</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">log</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F">'当前正在执行动作'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">)</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">            return</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        }</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">motion</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F">'任意动作对象'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">);</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    });</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">};</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//页面dom构建完成就执行</span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">onMounted</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">async</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> () </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=></span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    app</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80"> new</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> PIXI</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">Application</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">({</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        view</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> liveCanvas</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value, </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//ref组件绑定，liveCanvas为下文自定义的</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        autoStart</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> true</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//是否开启自动播放</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">        //resizeTo: window, //是否覆盖样式</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        interaction</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> true</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">// 确保启用交互系统</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        backgroundAlpha</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> 0</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">//背景</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        resolution</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> window</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">devicePixelRatio </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">||</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> 1</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">// 使用设备像素比提高清晰度</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        antialias</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> true</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">, </span><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">// 开启抗锯齿</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    })</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">    // 初始加载模型</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">    await</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> loadModel</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(model_num</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value);</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-light-font-style:italic;--shiki-dark:#859289;--shiki-dark-font-style:italic">    //监听动画是否正在执行</span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">    watchEffect</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(()</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=></span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">        if</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> (</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">!</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">||</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875"> !</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">internalModel) </span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">return</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">;</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        is_moving</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> model</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">internalModel?.motionManager</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">isFinished</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">()</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">        console</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">log</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F">'动画是否正在执行'</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">,is_moving</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">value )</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    })</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">})</span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">onBeforeUnmount</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">(() </span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">=></span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    model?.value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">destroy</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">()</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">    app?.value</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">destroy</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">()</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">})</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="构建页面" tabindex="-1"><a class="header-anchor" href="#构建页面"><span>构建页面</span></a></h2>
<div class="language-vue line-numbers-mode" data-highlighter="shiki" data-ext="vue" style="--shiki-light:#5c6a72;--shiki-dark:#d3c6aa;--shiki-light-bg:#fdf6e3;--shiki-dark-bg:#2d353b"><pre class="shiki shiki-themes everforest-light everforest-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">&#x3C;</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">template</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">  &#x3C;</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">div</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> class</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">"background"</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">    &#x3C;</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">div</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> class</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">"live2d-box"</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">      &#x3C;</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">canvas</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> class</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">"live2d-box-canvas"</span><span style="--shiki-light:#DFA000;--shiki-dark:#DBBC7F"> ref</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">=</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">"liveCanvas"</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">>&#x3C;/</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">canvas</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">    &#x3C;/</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">div</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">  &#x3C;/</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">div</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span>
<span class="line"><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">&#x3C;/</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">template</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-css line-numbers-mode" data-highlighter="shiki" data-ext="css" style="--shiki-light:#5c6a72;--shiki-dark:#d3c6aa;--shiki-light-bg:#fdf6e3;--shiki-dark-bg:#2d353b"><pre class="shiki shiki-themes everforest-light everforest-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">background</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    box-sizing</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> border-box</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    width</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> 100</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">vw</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    height</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> 100</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">vh</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    background-color</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#DF69BA;--shiki-dark:#D699B6"> aquamarine</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    display</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> flex</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    justify-content</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> center</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    align-items</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> center</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    flex-direction</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> column</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    overflow</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> hidden</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">}</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">live2d-box</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    width</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> 100</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">%</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    height</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> 100</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">%</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    display</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> flex</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    justify-content</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> center</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    align-items</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> center</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">}</span></span>
<span class="line"><span style="--shiki-light:#939F91;--shiki-dark:#859289">.</span><span style="--shiki-light:#F85552;--shiki-dark:#E67E80">live2d-box-canvas</span><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA"> {</span></span>
<span class="line"><span style="--shiki-light:#35A77C;--shiki-dark:#83C092">    height</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">:</span><span style="--shiki-light:#8DA101;--shiki-dark:#A7C080"> 100</span><span style="--shiki-light:#F57D26;--shiki-dark:#E69875">%</span><span style="--shiki-light:#939F91;--shiki-dark:#859289">;</span></span>
<span class="line"><span style="--shiki-light:#5C6A72;--shiki-dark:#D3C6AA">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="结束" tabindex="-1"><a class="header-anchor" href="#结束"><span>结束</span></a></h2>
<p>在vue中开始运行你的live2d模型吧! 😃 🎉</p>
</div></template>


